### ISSUE TITLE
index.html: Change description text

### ISSUE THREAD

**Issue by ihsavru** [ihsavru/30-days-of-code#6]
Change 
"A coding challenge inspired by Jennifer Dewalt where I am going to code every day for a month starting July 21, 2017."
 to
"A coding challenge inspired by Jennifer Dewalt where I am going to code every day for 30 days from July 21, 2017 to August 19,2017."

**Comment by ihsavru** [comment]
@Shreya001

**Comment by zmunro** [comment]
I think I can do this :)
